server:
  port: 8099

#执行器配置
xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    accessToken:
    executor:
      appname: testExecutor
      addresses:
      ip:
      port: 9966
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

#日志配置
logging:
  config: classpath:logback.xml

# mysql数据库访问配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: ''

# 中山IB库
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://jk.mywind.com.cn:8086/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    username: heziguang
#    password: heziguang@sz


#虚拟机IB库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.72:5029/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 191111


mybatis:
  type-aliases-package: com.demo.mapper
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true